#ifndef __Constant_h__
#define __Constant_h__

#define APPLICATION_WIDTH	600
#define APPLICATION_HEIGHT	500 
#define WIDGET_PANEL_WIDTH	150
#define WIDGET_Y0			30
#define WIDGET_Y_STEP		50
#define APP_NAME "M1102 Skeleton 1.0"

enum
{
	ID_QUIT = 1,
	ID_ABOUT,
	ID_LOAD,
	ID_SAVE,
	ID_BUTTON_LINE,
	ID_BUTTON_CIRCLE,
	ID_COLOR_FILL,
	ID_COLOR_STROKE,
	ID_SLIDER_STROKE,
	ID_CHECKBOX1
};

#endif